const DEFAULT_PAGEBUILDER_COLLECTION = 'api::page.page';
const DEFAULT_PAGEBUILDER_PATH_FIELD = 'path';
const DEFAULT_PAGEBUILDER_PLATFORM_UID = 'api::platform.platform';

export { DEFAULT_PAGEBUILDER_COLLECTION, DEFAULT_PAGEBUILDER_PATH_FIELD, DEFAULT_PAGEBUILDER_PLATFORM_UID };
